# This is a basic workflow to help you get started with Actions

name: ROS2 CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.1
      # Run the generator and output the results to a file.
      - run: |
          rosinstall_generator lidar_processor --rosdistro galactic \
          --deps-only --deps --upstream-development > /tmp/deps.repos
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: lidar_processor
          target-ros2-distro: galactic
          vcs-repo-file-url: /tmp/deps.repos
      
      
